TEMPLATEROOT = ../Template_F10x

# compilation flags for gdb

CFLAGS  = -O1 -g3
ASFLAGS = -g3

# object files

OBJS=  $(STARTUP) main.o stm32f10x_gpio.o stm32f10x_rcc.o stm32f10x_tim.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common


